### ISSUE TITLE
codelab - lv. 10 and 11 - Jump command not working

### ISSUE THREAD

**Issue by PabloB11** [google/santa-tracker-web#47]
Hi,
There is a problem with jump command on level 10 and 11 in codelab (https://santatracker.google.com/codelab.html)
Santa jumps up and returns to start position.
Tried in Firefox 83 and Chrome 87.0.4280.88 64-bit. 
I'm not the only person having this issue.

**Comment by samthor** [comment]
Thanks! We'll look at this on Monday.

**Comment by janjanneck** [comment]
Any updates? Jump in both levels isn’t working on latest public Chrome on macOS. Santa just jumps in place or back to the starting position

**Comment by samthor** [comment]
So you can skip to the specific level to try out the issue by appending "?level=11" to the HTML, like this: https://santatracker.google.com/codelab.html?level=11

I actually can't reproduce this issue on my machine (macOS, Chrome 87.0.4280.88)—it works fine. I believe it doesn't work though, I've seen folks upload images or gifs.

If there's any more information or anything interesting in the console I'd appreciate that.

**Comment by Ft-Helmholtz** [comment]
Thanks for the workaround.
Here I can reproduce it on any Windows 10 machine in the current Firefox or Edge. No ad-blockers or anything activated. Very curious!

Merry Christmas!!

**Comment by ruifigueiredo19** [comment]
There is a possibility that the bug is caused by the language.

If I load the page using the [english version](https://santatracker.google.com/intl/en/codelab.html?level=11) then jumping works. Checking the console, there is a call to `api.moveJump('block_id_7', 1, 'north');`.

On the other hand, when using the page on a different language, instead of `'north'`, the direction string passed is translated to the new language and the jumping mechanic fails in all of them, ie:
- Opening in [dutch](https://santatracker.google.com/intl/nl/codelab.html?level=11) the call is `api.moveJump('block_id_7', 1, 'noorden');`
- Opening in [german](https://santatracker.google.com/intl/de/codelab.html?level=11) the call is `api.moveJump('block_id_7', 1, 'Norden');`
- Opening in [italian](https://santatracker.google.com/intl/it/codelab.html?level=11) the call is `api.moveJump('block_id_7', 1, 'nord');`


I have reproduced this bug/behaviour using Windows 10 with Google Chrome Version 87.0.4280.88 and with Ubuntu 20.04 with Google Chrome Version 87.0.4280.88 as well

**Comment by Ft-Helmholtz** [comment]
That's it! If changed to English, it also works just fine. Good thinking!

**Comment by samthor** [comment]
Thank you for finding the problem! I'll try to fix this in the next couple of days, we are understandably taking a break from work for a bit.
